import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const rawline = localFont({
  variable: "--font-rawline",
  display: "swap",
  preload: true,
  src: [
    {
      path: "./rawline-400.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "./rawline-500.ttf",
      weight: "500",
      style: "normal"
    },
    {
      path: "./rawline-600.ttf",
      weight: "600",
      style: "normal"
    },
    {
      path: "./rawline-700.ttf",
      weight: "700",
      style: "normal"
    },
  ]
})

export const metadata: Metadata = {
  title: "Zumira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rawline.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
