export default function Autogestao(){
  return (
    <div>
      <h1>Autogestão</h1>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
      <p>teste</p>
    </div>
  )
}
